<a href="https://colab.research.google.com/github/sanikagurav/Python-Programming/blob/main/featureScaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#importing the database
dataset = pd.read_csv('Student.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Sanika' 8.0 19.0]
 ['Anuja' 7.0 20.0]
 ['Sakshi' nan 21.0]
 ['Saee' 6.0 nan]
 ['Gaytri' 7.5 20.0]
 ['Manjusha' 8.5 20.0]
 ['Divya' 7.0 21.0]]


In [ ]:
print(y)

['YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO']


In [ ]:
#Taking care of missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Sanika' 8.0 19.0]
 ['Anuja' 7.0 20.0]
 ['Sakshi' 7.333333333333333 21.0]
 ['Saee' 6.0 20.166666666666668]
 ['Gaytri' 7.5 20.0]
 ['Manjusha' 8.5 20.0]
 ['Divya' 7.0 21.0]]


In [ ]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 8.0 19.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 7.0 20.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 7.333333333333333 21.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 6.0 20.166666666666668]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 7.5 20.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 8.5 20.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 7.0 21.0]]


In [ ]:
# Encoding the Dependent Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 1 0 0 1 1 0]


In [ ]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 7.0 20.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 8.0 19.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 7.5 20.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 6.0 20.166666666666668]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 8.5 20.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 7.0 21.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 7.333333333333333 21.0]]


In [ ]:
print(y_train)

[1 1 1 0 1]


In [ ]:
print(y_train)

[1 1 1 0 1]


In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[ 2.          0.         -0.5        -0.5        -0.5         0.
  -0.5        -0.46499055  0.39528471]
 [-0.5         0.         -0.5        -0.5        -0.5         0.
   2.          0.69748583 -1.97642354]
 [-0.5         0.          2.         -0.5        -0.5         0.
  -0.5         0.11624764  0.39528471]
 [-0.5         0.         -0.5        -0.5         2.          0.
  -0.5        -1.62746694  0.79056942]
 [-0.5         0.         -0.5         2.         -0.5         0.
  -0.5         1.27872403  0.39528471]]


In [ ]:
print(x_test)

[[ 0.  1.  0.  0.  0. -1.  0. -1.  0.]
 [ 0. -1.  0.  0.  0.  1.  0.  1.  0.]]
